apiVersion: apps/v1
kind: Deployment
metadata:
  name: MyJavaApp-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: jdk
  template:
    metadata:
      labels:
        app: jdk
    spec:
      containers:
      - name: MyJavaApp-container
        image: saad854/MyJavAppImage:latest
        ports:
        - containerPort: 8080


---

apiVersion: v1 
kind: Service 
metadata: 
  name: MyJavaApp-svc
spec:
  selector:
    app: jdk
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 8080 
